<?php

use Illuminate\Database\Seeder;
use App\Municipio;

class MunicipioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //atlantida
        $municipio = new Municipio();
        $municipio ->municipio ="La Ceiba";
        $municipio ->idDepartamento ="1";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Tela";
        $municipio ->idDepartamento ="1";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Jutiapa";
        $municipio ->idDepartamento ="1";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="La Masica";
        $municipio ->idDepartamento ="1";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Francisco";
        $municipio ->idDepartamento ="1";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Arizona";
        $municipio ->idDepartamento ="1";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Esparta";
        $municipio ->idDepartamento ="1";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="El Porvenir";
        $municipio ->idDepartamento ="1";
        $municipio ->save();

        //colon
        $municipio = new Municipio();
        $municipio ->municipio ="Trujillo";
        $municipio ->idDepartamento ="2";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Balfate";
        $municipio ->idDepartamento ="2";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Iriona";
        $municipio ->idDepartamento ="2";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Limón";
        $municipio ->idDepartamento ="2";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Sabá";
        $municipio ->idDepartamento ="2";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Santa Fe";
        $municipio ->idDepartamento ="2";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Santa Rosa de Aguán";
        $municipio ->idDepartamento ="2";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Sonaguera";
        $municipio ->idDepartamento ="2";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Tocoa";
        $municipio ->idDepartamento ="2";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Bonito Oriental";
        $municipio ->idDepartamento ="2";
        $municipio ->save();


        //comayagua
        $municipio = new Municipio();
        $municipio ->municipio ="Comayagua";
        $municipio ->idDepartamento ="3";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Ajuterique";
        $municipio ->idDepartamento ="3";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="El Rosario";
        $municipio ->idDepartamento ="3";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Esquías";
        $municipio ->idDepartamento ="3";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Humuya";
        $municipio ->idDepartamento ="3";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="La Libertad";
        $municipio ->idDepartamento ="3";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Lamaní";
        $municipio ->idDepartamento ="3";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="La Trinidad";
        $municipio ->idDepartamento ="3";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Lejamani";
        $municipio ->idDepartamento ="3";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Meambar";
        $municipio ->idDepartamento ="3";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Minas de Oro";
        $municipio ->idDepartamento ="3";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Ojos de Agua";
        $municipio ->idDepartamento ="3";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Jerónimo";
        $municipio ->idDepartamento ="3";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San José de Comayagua";
        $municipio ->idDepartamento ="3";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San José del Potrero";
        $municipio ->idDepartamento ="3";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Luis";
        $municipio ->idDepartamento ="3";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Sebastián";
        $municipio ->idDepartamento ="3";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Siguatepeque";
        $municipio ->idDepartamento ="3";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Villa de San Antonio";
        $municipio ->idDepartamento ="3";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Las Lajas";
        $municipio ->idDepartamento ="3";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Taulabé";
        $municipio ->idDepartamento ="3";
        $municipio ->save();


        //copan
        $municipio = new Municipio();
        $municipio ->municipio ="Santa Rosa de Copán";
        $municipio ->idDepartamento ="4";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Cabañas";
        $municipio ->idDepartamento ="4";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Concepción";
        $municipio ->idDepartamento ="4";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Copán Ruinas";
        $municipio ->idDepartamento ="4";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Corquín";
        $municipio ->idDepartamento ="4";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Cucuyagua";
        $municipio ->idDepartamento ="4";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Dolores";
        $municipio ->idDepartamento ="4";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Dulce Nombre";
        $municipio ->idDepartamento ="4";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="El Paraíso";
        $municipio ->idDepartamento ="4";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Florida";
        $municipio ->idDepartamento ="4";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="La Jigua";
        $municipio ->idDepartamento ="4";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="La Unión";
        $municipio ->idDepartamento ="4";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Nueva Arcadia";
        $municipio ->idDepartamento ="4";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Antonio";
        $municipio ->idDepartamento ="4";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Jerónimo";
        $municipio ->idDepartamento ="4";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San José";
        $municipio ->idDepartamento ="4";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Juan de Opoa";
        $municipio ->idDepartamento ="4";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Nicolás";
        $municipio ->idDepartamento ="4";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Pedro";
        $municipio ->idDepartamento ="4";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Santa Rita";
        $municipio ->idDepartamento ="4";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Trinidad de Copán";
        $municipio ->idDepartamento ="4";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Veracruz";
        $municipio ->idDepartamento ="4";
        $municipio ->save();

        //cortes
        $municipio ->municipio ="San Pedro Sula";
        $municipio ->idDepartamento ="5";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Choloma";
        $municipio ->idDepartamento ="5";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Omoa";
        $municipio ->idDepartamento ="5";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Pimienta";
        $municipio ->idDepartamento ="5";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Potrerillos";
        $municipio ->idDepartamento ="5";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Puerto Cortés";
        $municipio ->idDepartamento ="5";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Antonio de Cortés";
        $municipio ->idDepartamento ="5";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Francisco de Yojoa";
        $municipio ->idDepartamento ="5";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Manuel";
        $municipio ->idDepartamento ="5";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Santa Cruz de Yojoa";
        $municipio ->idDepartamento ="5";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Villanueva";
        $municipio ->idDepartamento ="5";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="La Lima";
        $municipio ->idDepartamento ="5";
        $municipio ->save();

        //choluteca
        $municipio ->municipio ="Choluteca";
        $municipio ->idDepartamento ="6";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Apacilagua";
        $municipio ->idDepartamento ="6";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Concepción de María";
        $municipio ->idDepartamento ="6";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Duyure";
        $municipio ->idDepartamento ="6";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="El Corpus";
        $municipio ->idDepartamento ="6";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="El Triunfo";
        $municipio ->idDepartamento ="6";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Marcovia";
        $municipio ->idDepartamento ="6";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Morolica";
        $municipio ->idDepartamento ="6";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Namasigue";
        $municipio ->idDepartamento ="6";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Orocuina";
        $municipio ->idDepartamento ="6";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Pespire";
        $municipio ->idDepartamento ="6";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Antonio de Flores";
        $municipio ->idDepartamento ="6";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Isidro";
        $municipio ->idDepartamento ="6";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San José";
        $municipio ->idDepartamento ="6";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Marcos de Colón";
        $municipio ->idDepartamento ="6";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Santa Ana de Yusguare";
        $municipio ->idDepartamento ="6";
        $municipio ->save();

        //el paraiso
        $municipio ->municipio ="Yuscarán";
        $municipio ->idDepartamento ="7";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Alauca";
        $municipio ->idDepartamento ="7";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Danlí";
        $municipio ->idDepartamento ="7";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="El Paraíso";
        $municipio ->idDepartamento ="7";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Güinope";
        $municipio ->idDepartamento ="7";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Jacaleapa";
        $municipio ->idDepartamento ="7";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Liure";
        $municipio ->idDepartamento ="7";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Morocelí";
        $municipio ->idDepartamento ="7";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Oropolí";
        $municipio ->idDepartamento ="7";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Potrerillos";
        $municipio ->idDepartamento ="7";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Antonio de Flores";
        $municipio ->idDepartamento ="7";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Lucas";
        $municipio ->idDepartamento ="7";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Matías";
        $municipio ->idDepartamento ="7";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Soledad";
        $municipio ->idDepartamento ="7";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Teupasenti";
        $municipio ->idDepartamento ="7";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Texiguat";
        $municipio ->idDepartamento ="7";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Vado Ancho";
        $municipio ->idDepartamento ="7";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Yauyupe";
        $municipio ->idDepartamento ="7";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Trojes";
        $municipio ->idDepartamento ="7";
        $municipio ->save();

        //francisco morazan
        $municipio ->municipio ="Distrito Central";
        $municipio ->idDepartamento ="8";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Alubarén";
        $municipio ->idDepartamento ="8";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Cedros";
        $municipio ->idDepartamento ="8";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Curarén";
        $municipio ->idDepartamento ="8";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="El Porvenir";
        $municipio ->idDepartamento ="8";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Guaimaca";
        $municipio ->idDepartamento ="8";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="La Libertad";
        $municipio ->idDepartamento ="8";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="La Venta";
        $municipio ->idDepartamento ="8";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Lepaterique";
        $municipio ->idDepartamento ="8";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Maraita";
        $municipio ->idDepartamento ="8";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Marale";
        $municipio ->idDepartamento ="8";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Nueva Armenia";
        $municipio ->idDepartamento ="8";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Ojojona";
        $municipio ->idDepartamento ="8";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Orica";
        $municipio ->idDepartamento ="8";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Reitoca";
        $municipio ->idDepartamento ="8";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Sabanagrande";
        $municipio ->idDepartamento ="8";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Antonio de Oriente";
        $municipio ->idDepartamento ="8";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Buenaventura";
        $municipio ->idDepartamento ="8";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Ignacio";
        $municipio ->idDepartamento ="8";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Juan de Flores";
        $municipio ->idDepartamento ="8";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Miguelito";
        $municipio ->idDepartamento ="8";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Santa Ana";
        $municipio ->idDepartamento ="8";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Santa Lucía";
        $municipio ->idDepartamento ="8";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Talanga";
        $municipio ->idDepartamento ="8";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Tatumbla";
        $municipio ->idDepartamento ="8";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Valle de Ángeles";
        $municipio ->idDepartamento ="8";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Villa de San Francisco";
        $municipio ->idDepartamento ="8";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Vallecillo";
        $municipio ->idDepartamento ="8";
        $municipio ->save();

        //Gracias a Dios
        $municipio = new Municipio();
        $municipio ->municipio ="Puerto Lempira";
        $municipio ->idDepartamento ="9";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Brus Laguna";
        $municipio ->idDepartamento ="9";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Ahuas";
        $municipio ->idDepartamento ="9";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Juan Francisco Bulnes";
        $municipio ->idDepartamento ="9";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Ramón Villeda Morales";
        $municipio ->idDepartamento ="9";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Wampusirpe";
        $municipio ->idDepartamento ="9";
        $municipio ->save();


        //intibuca
        $municipio = new Municipio();
        $municipio ->municipio ="La Esperanza";
        $municipio ->idDepartamento ="10";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Camasca";
        $municipio ->idDepartamento ="10";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Colomoncagua";
        $municipio ->idDepartamento ="10";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Concepción";
        $municipio ->idDepartamento ="10";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Dolores";
        $municipio ->idDepartamento ="10";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Intibucá";
        $municipio ->idDepartamento ="10";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Jesús de Otoro";
        $municipio ->idDepartamento ="10";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Magdalena";
        $municipio ->idDepartamento ="10";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Masaguara";
        $municipio ->idDepartamento ="10";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Antonio";
        $municipio ->idDepartamento ="10";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Isidro";
        $municipio ->idDepartamento ="10";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Juan";
        $municipio ->idDepartamento ="10";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Marcos de la Sierra";
        $municipio ->idDepartamento ="10";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Miguel Guancapla";
        $municipio ->idDepartamento ="10";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Santa Lucía";
        $municipio ->idDepartamento ="10";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Yamaranguila";
        $municipio ->idDepartamento ="10";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Francisco de Opalaca";
        $municipio ->idDepartamento ="10";
        $municipio ->save();

        //islas de  la bahia
        $municipio = new Municipio();
        $municipio ->municipio ="Roatán";
        $municipio ->idDepartamento ="11";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Guanaja";
        $municipio ->idDepartamento ="11";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="José Santos Guardiola";
        $municipio ->idDepartamento ="11";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Utila";
        $municipio ->idDepartamento ="11";
        $municipio ->save();


        //paz
        $municipio = new Municipio();
        $municipio ->municipio ="La Paz";
        $municipio ->idDepartamento ="12";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Aguanqueterique";
        $municipio ->idDepartamento ="12";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Cabañas";
        $municipio ->idDepartamento ="12";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Cane";
        $municipio ->idDepartamento ="12";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Chinacla";
        $municipio ->idDepartamento ="12";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Guajiquiro";
        $municipio ->idDepartamento ="12";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Lauterique";
        $municipio ->idDepartamento ="12";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Marcala";
        $municipio ->idDepartamento ="12";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Mercedes de Oriente";
        $municipio ->idDepartamento ="12";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Opatoro";
        $municipio ->idDepartamento ="12";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Antonio del Norte";
        $municipio ->idDepartamento ="12";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San José";
        $municipio ->idDepartamento ="12";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Juan";
        $municipio ->idDepartamento ="12";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Pedro de Tutule";
        $municipio ->idDepartamento ="12";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Santa Ana";
        $municipio ->idDepartamento ="12";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Santa Elena";
        $municipio ->idDepartamento ="12";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Santa María";
        $municipio ->idDepartamento ="12";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Santiago de Puringla";
        $municipio ->idDepartamento ="12";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Santiago de Puringla";
        $municipio ->idDepartamento ="12";
        $municipio ->save();

        //lempira

        $municipio = new Municipio();
        $municipio ->municipio ="Gracias";
        $municipio ->idDepartamento ="13";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Belén";
        $municipio ->idDepartamento ="13";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Candelaria";
        $municipio ->idDepartamento ="13";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Cololaca";
        $municipio ->idDepartamento ="13";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Erandique";
        $municipio ->idDepartamento ="13";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Gualcince";
        $municipio ->idDepartamento ="13";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Guarita";
        $municipio ->idDepartamento ="13";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="La Campa";
        $municipio ->idDepartamento ="13";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="La Iguala";
        $municipio ->idDepartamento ="13";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Las Flores";
        $municipio ->idDepartamento ="13";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="La Unión";
        $municipio ->idDepartamento ="13";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="La Virtud";
        $municipio ->idDepartamento ="13";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Lepaera";
        $municipio ->idDepartamento ="13";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Mapulaca";
        $municipio ->idDepartamento ="13";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Piraera";
        $municipio ->idDepartamento ="13";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Andrés";
        $municipio ->idDepartamento ="13";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Francisco";
        $municipio ->idDepartamento ="13";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Juan Guarita";
        $municipio ->idDepartamento ="13";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Manuel Colohete";
        $municipio ->idDepartamento ="13";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Rafael";
        $municipio ->idDepartamento ="13";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Sebastián";
        $municipio ->idDepartamento ="13";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Santa Cruz";
        $municipio ->idDepartamento ="13";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Talgua";
        $municipio ->idDepartamento ="13";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Tambla";
        $municipio ->idDepartamento ="13";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Tomalá";
        $municipio ->idDepartamento ="13";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Valladolid";
        $municipio ->idDepartamento ="13";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Virginia";
        $municipio ->idDepartamento ="13";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Marcos de Caiquín";
        $municipio ->idDepartamento ="13";
        $municipio ->save();


        //ocotepeque
        $municipio = new Municipio();
        $municipio ->municipio ="Ocotepeque";
        $municipio ->idDepartamento ="14";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Belén Gualcho";
        $municipio ->idDepartamento ="14";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Concepción";
        $municipio ->idDepartamento ="14";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Dolores Merendón";
        $municipio ->idDepartamento ="14";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Fraternidad";
        $municipio ->idDepartamento ="14";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="La Encarnación";
        $municipio ->idDepartamento ="14";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="La Labor";
        $municipio ->idDepartamento ="14";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Lucerna";
        $municipio ->idDepartamento ="14";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Mercedes";
        $municipio ->idDepartamento ="14";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Fernando";
        $municipio ->idDepartamento ="14";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Francisco del Valle";
        $municipio ->idDepartamento ="14";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Jorge";
        $municipio ->idDepartamento ="14";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Marcos";
        $municipio ->idDepartamento ="14";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Santa Fe";
        $municipio ->idDepartamento ="14";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Sensenti";
        $municipio ->idDepartamento ="14";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Sinuapa";
        $municipio ->idDepartamento ="14";
        $municipio ->save();

        //Olancho
        $municipio = new Municipio();
        $municipio ->municipio ="Juticalpa";
        $municipio ->idDepartamento ="15";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Campamento";
        $municipio ->idDepartamento ="15";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Catacamas";
        $municipio ->idDepartamento ="15";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Concordia";
        $municipio ->idDepartamento ="15";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Dulce Nombre de Culmí";
        $municipio ->idDepartamento ="15";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="El Rosario";
        $municipio ->idDepartamento ="15";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Esquipulas del Norte";
        $municipio ->idDepartamento ="15";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Gualaco";
        $municipio ->idDepartamento ="15";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Guarizama";
        $municipio ->idDepartamento ="15";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Guata";
        $municipio ->idDepartamento ="15";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Guayape";
        $municipio ->idDepartamento ="15";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Jano";
        $municipio ->idDepartamento ="15";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="La Unión";
        $municipio ->idDepartamento ="15";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Mangulile";
        $municipio ->idDepartamento ="15";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Manto";
        $municipio ->idDepartamento ="15";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Salamá";
        $municipio ->idDepartamento ="15";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Esteban";
        $municipio ->idDepartamento ="15";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Francisco de Becerra";
        $municipio ->idDepartamento ="15";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Francisco de la Paz";
        $municipio ->idDepartamento ="15";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Santa María del Real";
        $municipio ->idDepartamento ="15";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Silca";
        $municipio ->idDepartamento ="15";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Yocón";
        $municipio ->idDepartamento ="15";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Patuca";
        $municipio ->idDepartamento ="15";
        $municipio ->save();


        //barbara
        $municipio = new Municipio();
        $municipio ->municipio ="Santa Bárbara";
        $municipio ->idDepartamento ="16";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Arada";
        $municipio ->idDepartamento ="16";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Atima";
        $municipio ->idDepartamento ="16";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Azacualpa";
        $municipio ->idDepartamento ="16";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Ceguaca";
        $municipio ->idDepartamento ="16";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Concepción del Norte";
        $municipio ->idDepartamento ="16";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Concepción del Sur";
        $municipio ->idDepartamento ="16";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Chinda";
        $municipio ->idDepartamento ="16";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="El Níspero";
        $municipio ->idDepartamento ="16";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Gualala";
        $municipio ->idDepartamento ="16";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Ilama";
        $municipio ->idDepartamento ="16";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Las Vegas";
        $municipio ->idDepartamento ="16";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Macuelizo";
        $municipio ->idDepartamento ="16";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Naranjito";
        $municipio ->idDepartamento ="16";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Nuevo Celilac";
        $municipio ->idDepartamento ="16";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Nueva Frontera";
        $municipio ->idDepartamento ="16";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Petoa";
        $municipio ->idDepartamento ="16";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Protección";
        $municipio ->idDepartamento ="16";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Quimistán";
        $municipio ->idDepartamento ="16";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Francisco de Ojuera";
        $municipio ->idDepartamento ="16";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San José de las Colinas";
        $municipio ->idDepartamento ="16";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Luis";
        $municipio ->idDepartamento ="16";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Marcos";
        $municipio ->idDepartamento ="16";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Nicolás";
        $municipio ->idDepartamento ="16";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Pedro Zacapa";
        $municipio ->idDepartamento ="16";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Vicente Centenario";
        $municipio ->idDepartamento ="16";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Santa Rita";
        $municipio ->idDepartamento ="16";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Trinidad";
        $municipio ->idDepartamento ="16";
        $municipio ->save();

        //valle

        $municipio ->municipio ="Nacaome";
        $municipio ->idDepartamento ="17";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Alianza";
        $municipio ->idDepartamento ="17";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Amapala";
        $municipio ->idDepartamento ="17";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Aramecina";
        $municipio ->idDepartamento ="17";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Caridad";
        $municipio ->idDepartamento ="17";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Goascorán";
        $municipio ->idDepartamento ="17";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Langue";
        $municipio ->idDepartamento ="17";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Francisco de Coray";
        $municipio ->idDepartamento ="17";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="San Lorenzo";
        $municipio ->idDepartamento ="17";
        $municipio ->save();


        //yoro
        $municipio = new Municipio();
        $municipio ->municipio ="Yoro";
        $municipio ->idDepartamento ="18";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Arenal";
        $municipio ->idDepartamento ="18";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="El Negrito";
        $municipio ->idDepartamento ="18";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="El Progreso";
        $municipio ->idDepartamento ="18";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Jocón";
        $municipio ->idDepartamento ="18";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Morazán";
        $municipio ->idDepartamento ="18";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Olanchito";
        $municipio ->idDepartamento ="18";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Santa Rita";
        $municipio ->idDepartamento ="18";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Sulaco";
        $municipio ->idDepartamento ="18";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Victoria";
        $municipio ->idDepartamento ="18";
        $municipio ->save();
        $municipio = new Municipio();
        $municipio ->municipio ="Yorito";
        $municipio ->idDepartamento ="18";
        $municipio ->save();
    }
}
